name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        # https://github.com/actions/setup-java#supported-distributions
        distribution: 'zulu'
        java-version: 11

    - name: Build with Maven
      run: mvn --no-transfer-progress package --file pom.xml

    - name: Archive mp3 file
      uses: actions/upload-artifact@v3
      with:
        name: mp3 file
        path: target/hello_world.mp3
    
    # - name: SonarCloud
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   run: mvn --no-transfer-progress clean verify sonar:sonar
